### ISSUE TITLE
Some of the examples do not work

### ISSUE THREAD

**Issue by SheetJSDev** [githubocto/flat-postprocessing#11]
Starting from scratch:

```bash
$ deno --version
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
$ cd /tmp
$ git clone --depth=1 https://github.com/githubocto/flat-postprocessing
$ cd flat-postprocessing/
$ for i in examples/*/*.ts; do echo "$i"; deno run -A --unstable "$i"; done
```

Failing examples:

- examples/csv/arquero-example.ts issue with the actual skypack bundle

```
error: Relative import path "acorn" not prefixed with / or ./ or ../
    at https://cdn.skypack.dev/-/arquero@v4.8.8-dWXL1bFb2EbzIQrDNAMi/dist=es2019,mode=imports/optimized/arquero.js:2:34
```

- examples/image/image-example.ts https://api.creativecommons.engineering/v1/thumbs/c8fe5f5b-cc1a-4794-91c5-7488c60f4914 is no longer available (#10 had to change the image test to correct for this)

```
error: Uncaught (in promise) Error: Unsupported image type
        } else throw new Error('Unsupported image type');
                     ^
    at Function.decode (https://cdn.deno.land/imagescript/versions/1.2.0/raw/ImageScript.js:1184:22)
    at file:///private/tmp/flat-postprocessing/examples/image/image-example.ts:21:27
```

- examples/sheets/sheets-example.ts Google Sheets v3 API was deprecated in August 2021

```
error: Uncaught (in promise) Error: unmatched close-tag near '</head><'
          throw new Error(
                ^
    at Parser.parse (https://deno.land/x/xmlparser@v0.2.0/parser.ts:88:17)
    at file:///private/tmp/flat-postprocessing/examples/sheets/sheets-example.ts:17:21
```

**Comment by irealva** [comment]
Thank you for pointing this out, we've fixed the examples.
